### ISSUE TITLE
Add support for controlling random seeds

### ISSUE THREAD

**Issue by kephale** [anmartinezs/polnet#14]
It currently isn't possible to reproduce an exact run on polnet because the `polnet.lrandom` does not let the user seed the random number generator/use the same RNG for all random calls.

I'd be happy to take this on if ya'll are interested, but regardless would strongly advocate for this functionality.

**Comment by anmartinezs** [comment]
Sorry for late answer. This is a great idea, are you still interested into take this on?

**Comment by kephale** [comment]
I've started: https://github.com/anmartinezs/polnet/pull/16

Currently tests aren't passing. I haven't fully diagnosed the source yet.

**Comment by kephale** [comment]
Just checking in on this @anmartinezs. :)

**Comment by anmartinezs** [comment]
OK, we understand that you pull request is ready for being merged, we will handle this soon. Many thanks for your contribution.

**Comment by kephale** [comment]
Great, thank you!
