### ISSUE TITLE
.pns input files: how to generate

### ISSUE THREAD

**Issue by jmdobbs** [anmartinezs/polnet#2]
Hi,

Looking at the (nice) simulator you have, I see that you have the input as .pns, .hns and .mbs files. In the template generation script you provide, however, the output is in mrc. 

edit: realized that it's just a pointer text file, sorry :P

Thanks!
Joe

**Comment by anmartinezs** [comment]
Nice to see that the issue was solved by yourself. Currently, we're working on improving the simulator and prividing a GUI to prepare the input models for macromolecules, specially for membrane bound proteins this is time consuming task.

Best
