### ISSUE TITLE
How to generate specific number of membranes or proteins?

### ISSUE THREAD

**Issue by Fizza-Rubab** [anmartinezs/polnet#4]
Hi!

I want to add specific number of membranes, proteins or membrane proteins to the generated tomogram. For example, 5 membranes, 100 molecules etc. Is there any direct way to do that or where should I tweak the code to make it possible?

Thank you!

**Comment by anmartinezs** [comment]
There is no way of set a specific ammount of structures. However, you can control the concentration (volume_structure/volume_total) of every structure with the configuration files: .hns, mbs, .pns and .pms.

Sorry for the late answer.
